name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  end-to-end:
    name: End-to-end
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Install Playwright browsers
        run: yarn playwright install --with-deps
      - name: Run Playwright
        run: yarn run test:e2e
        env: ${{ secrets }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run Vitest
        run: npm run test:unit
        env: ${{ secrets }}